### ISSUE TITLE
Issue: Update

### ISSUE THREAD

**Issue by jsbono** [rajit/b3dp-21#1]
Thanks for your response! I was able to get your code to work locally, in the stripped down application exactly as you posted. However, in my app there's more going on so I didn't clone yours for debugging, rather I pieced mine apart until I found the culprit. It took me a handful of hours to isolate the error, but I think I may have it. I'm running iron router btw.

It appears that when I configure a layout attribute for Iron Router, and that layout references a template named "errors", I can reproduce the problem where the date picker locks up an doesn't allow you to select dates +/- 1 month from now. 

If I change the name of the errors template to a new name, like errors1, the date picker works as expected. I'm wondering if there is a conflicted name within your package? Or maybe my code is doing something it wasn't meant to. 

Unfortunately, in my primary app, simply changing the name of the errors template did not fix the issue, but I'm certain they are related as its the same behavior. 

There's 5 files to the app, which I'm attaching. Thanks for the help! Would love to get this to work.

[Archive.zip](https://github.com/rajit/b3dp-21/files/105921/Archive.zip)

**Comment by rajit** [comment]
I've updated the repository to fix some issues in your code.

You had a nested `<body/>` tag — one was appearing from `b3dp-21.html`, outside a template (this is the standard way of managing `<head/>` and `<body/>` in Meteor) and the other was injected by your layout template `layout`.

Your layout template was not calling `{{> yield}}` which means when it is used in a route, the template for that route would not be included.

With these issues fixed and with a template called `errors` present, I am currently seeing no issues with bootstrap3-datepicker.

Could you update your clone of this repository and see if it works for you as well?

**Comment by jsbono** [comment]
Thanks - eliminating the nested body tags made the ex. demo work, my primary app is in fact structured with body/head in a layout file outside of a template.

**Comment by rajit** [comment]
Have you managed to get your app working correctly?
